language: java
jdk:
  - openjdk8

branches:
  only:
    - deploy

## Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r shophere *
  - mkdir -p deploy
  - mv shophere.zip deploy/shophere.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      branch: deploy
    bucket: shophere-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: shophere-webservice-build
    key: shophere.zip
    build_type: zip
    application: shophere-webservice # AWS웹 콘솔에서 CodeDeploy 등록한 Name
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients: ghtjd5689@gmail.com